const PDFDocument = require('pdfkit');
const fs = require('fs');
const path = require('path');

// Helper to check if a file is a valid TTF font (checks magic bytes)
const isValidTTF = (filePath) => {
    try {
        if (!fs.existsSync(filePath)) return false;
        const buffer = fs.readFileSync(filePath);
        if (buffer.length < 4) return false;
        // TTF magic bytes: 0x00 0x01 0x00 0x00 or 'true' or 'OTTO'
        const magic = buffer.slice(0, 4).toString('hex');
        return magic === '00010000' || magic === '74727565' || magic === '4f54544f';
    } catch {
        return false;
    }
};

exports.generateInvoicePDF = (invoice, settings, res) => {
    const doc = new PDFDocument({ margin: 50, size: 'A4' });

    // Stream directly to response
    res.setHeader('Content-Type', 'application/pdf');
    res.setHeader('Content-Disposition', `attachment; filename=invoice-${invoice.id}.pdf`);
    doc.pipe(res);

    // --- Font Setup (Critical for Thai Support) ---
    const fontPath = path.join(__dirname, '../assets/fonts/Sarabun-Regular.ttf');
    const fontBoldPath = path.join(__dirname, '../assets/fonts/Sarabun-Bold.ttf');

    // Validate fonts are real TTF files
    const hasThaiFont = isValidTTF(fontPath);
    const hasBoldFont = isValidTTF(fontBoldPath);

    if (hasThaiFont) {
        try {
            doc.registerFont('ThaiRegular', fontPath);
            doc.font('ThaiRegular');
        } catch (err) {
            console.warn('Failed to load Thai font, using Helvetica:', err.message);
            doc.font('Helvetica');
        }
    } else {
        doc.font('Helvetica');
        console.warn('Thai font not found or invalid. Using English labels with Helvetica.');
    }

    if (hasBoldFont) {
        try {
            doc.registerFont('ThaiBold', fontBoldPath);
        } catch (err) {
            console.warn('Failed to load Thai bold font:', err.message);
        }
    }

    // --- Detect if this is a receipt (PAID) or invoice ---
    const isPaid = invoice.status === 'PAID';

    // Use English labels as fallback when Thai font is not available
    const labels = hasThaiFont ? {
        docTitle: isPaid ? 'ใบเสร็จรับเงิน' : 'ใบแจ้งหนี้',
        room: 'ห้อง',
        tenant: 'ผู้เช่า',
        invoiceNo: 'เลขที่',
        date: 'วันที่ออกบิล',
        dueDate: 'กำหนดชำระ',
        paid: 'สถานะ: ชำระแล้ว',
        description: 'รายการ',
        units: 'หน่วย',
        rate: 'ราคา/หน่วย',
        amount: 'จำนวนเงิน',
        rent: 'ค่าเช่าห้อง',
        water: 'ค่าน้ำประปา',
        electric: 'ค่าไฟฟ้า',
        month: 'เดือน',
        unit: 'หน่วย',
        total: 'รวมทั้งสิ้น',
        currency: 'บาท',
        paymentMethod: 'ช่องทางการชำระเงิน',
        promptPay: 'พร้อมเพย์',
        accountName: 'ชื่อบัญชี',
        note: '* กรุณาส่งสลิปหลักฐานการโอนเงินผ่านระบบหรือ Line',
        paidStamp: 'ชำระเงินแล้ว',
        footer: 'เอกสารนี้สร้างโดยระบบ'
    } : {
        docTitle: isPaid ? 'RECEIPT' : 'INVOICE',
        room: 'Room',
        tenant: 'Tenant',
        invoiceNo: 'No.',
        date: 'Date',
        dueDate: 'Due Date',
        paid: 'Status: PAID',
        description: 'Description',
        units: 'Units',
        rate: 'Rate',
        amount: 'Amount',
        rent: 'Room Rent',
        water: 'Water',
        electric: 'Electricity',
        month: 'month',
        unit: 'units',
        total: 'Total',
        currency: 'THB',
        paymentMethod: 'Payment Method',
        promptPay: 'PromptPay',
        accountName: 'Account Name',
        note: '* Please send payment slip via the system or Line',
        paidStamp: 'PAID',
        footer: 'Generated by'
    };

    const docPrefix = isPaid ? 'RCP' : 'INV';

    // --- Format Helpers ---
    const formatCurrency = (amount) => {
        return parseFloat(amount || 0).toLocaleString('th-TH', { minimumFractionDigits: 2, maximumFractionDigits: 2 });
    };

    const formatDate = (date) => {
        return new Date(date).toLocaleDateString('th-TH', {
            year: 'numeric', month: 'long', day: 'numeric'
        });
    };

    // ===== HEADER =====
    const useBold = () => {
        if (hasBoldFont) doc.font('ThaiBold');
        else if (hasThaiFont) doc.font('ThaiRegular');
        else doc.font('Helvetica-Bold');
    };

    const useRegular = () => {
        if (hasThaiFont) doc.font('ThaiRegular');
        else doc.font('Helvetica');
    };

    // Dorm Name
    useBold();
    doc.fontSize(22).text(settings.dormName || 'Dormitory', { align: 'center' });

    useRegular();
    doc.fontSize(10).text(settings.address || '', { align: 'center' });

    doc.moveDown(1);
    doc.moveTo(50, doc.y).lineTo(545, doc.y).stroke();
    doc.moveDown(0.5);

    // ===== DOCUMENT TITLE & INFO =====
    const headerY = doc.y;

    // Left side - Document title
    useBold();
    doc.fontSize(16).text(labels.docTitle, 50, headerY);

    useRegular();
    doc.fontSize(11);
    doc.text(`${labels.room}: ${invoice.room.roomNumber}`, 50, headerY + 25);
    doc.text(`${labels.tenant}: ${invoice.tenant.firstName} ${invoice.tenant.lastName}`, 50, headerY + 40);

    // Right side - Invoice info
    doc.fontSize(11);
    doc.text(`${labels.invoiceNo}: ${docPrefix}-${invoice.id.toString().padStart(6, '0')}`, 350, headerY, { align: 'right', width: 195 });
    doc.text(`${labels.date}: ${formatDate(invoice.billingMonth)}`, 350, headerY + 15, { align: 'right', width: 195 });

    if (isPaid) {
        doc.text(labels.paid, 350, headerY + 30, { align: 'right', width: 195 });
    } else {
        doc.text(`${labels.dueDate}: ${formatDate(invoice.dueDate)}`, 350, headerY + 30, { align: 'right', width: 195 });
    }

    doc.moveDown(4);

    // ===== TABLE HEADER =====
    const tableTop = doc.y;
    const col1 = 50;
    const col2 = 300;
    const col3 = 380;
    const col4 = 470;

    // Header row background
    doc.rect(50, tableTop - 5, 495, 25).fill('#f5f5f5');

    useBold();
    doc.fillColor('#000').fontSize(11);
    doc.text(labels.description, col1 + 5, tableTop);
    doc.text(labels.units, col2, tableTop);
    doc.text(labels.rate, col3, tableTop);
    doc.text(labels.amount, col4, tableTop);

    // ===== TABLE CONTENT =====
    useRegular();
    doc.fontSize(11);

    let y = tableTop + 30;
    const rowHeight = 25;

    // Row 1: Rent
    doc.text(labels.rent, col1 + 5, y);
    doc.text(`1 ${labels.month}`, col2, y);
    doc.text(formatCurrency(invoice.rentAmount), col3, y);
    doc.text(formatCurrency(invoice.rentAmount), col4, y);
    y += rowHeight;
    doc.moveTo(50, y - 5).lineTo(545, y - 5).stroke('#eee');

    // Row 2: Water
    doc.text(labels.water, col1 + 5, y);
    doc.text(`${invoice.waterUnits || 0} ${labels.unit}`, col2, y);
    doc.text(formatCurrency(settings.waterRate || 18), col3, y);
    doc.text(formatCurrency(invoice.waterAmount), col4, y);
    y += rowHeight;
    doc.moveTo(50, y - 5).lineTo(545, y - 5).stroke('#eee');

    // Row 3: Electricity
    doc.text(labels.electric, col1 + 5, y);
    doc.text(`${invoice.electricUnits || 0} ${labels.unit}`, col2, y);
    doc.text(formatCurrency(settings.electricRate || 8), col3, y);
    doc.text(formatCurrency(invoice.electricAmount), col4, y);
    y += rowHeight;

    // Bottom line
    doc.moveTo(50, y - 5).lineTo(545, y - 5).stroke('#000');

    // ===== TOTAL =====
    y += 10;
    useBold();
    doc.fontSize(14);
    doc.text(labels.total, col3 - 50, y);
    doc.text(`${formatCurrency(invoice.totalAmount)} ${labels.currency}`, col4 - 10, y);

    // ===== PAYMENT INFO =====
    doc.moveDown(4);
    useRegular();

    if (isPaid) {
        // Paid stamp
        const stampY = doc.y;
        doc.rect(180, stampY, 180, 60).lineWidth(3).stroke('#16a34a');
        useBold();
        doc.fillColor('#16a34a').fontSize(18).text(labels.paidStamp, 180, stampY + 10, { width: 180, align: 'center' });
        useRegular();
        doc.fontSize(10).text(formatDate(invoice.paidAt || new Date()), 180, stampY + 35, { width: 180, align: 'center' });
        doc.fillColor('#000');
    } else {
        // Payment instructions
        useBold();
        doc.fontSize(12).text(labels.paymentMethod);
        useRegular();
        doc.fontSize(10);
        doc.moveDown(0.5);
        doc.text(`${labels.promptPay}: ${settings.promptPayID || '-'}`);
        doc.text(`${labels.accountName}: ${settings.promptPayName || '-'}`);
        doc.moveDown(0.5);
        doc.fontSize(9).fillColor('#666').text(labels.note);
    }

    // ===== FOOTER =====
    doc.fillColor('#999').fontSize(8);
    doc.text(`${labels.footer} ${settings.brandName || 'DormManager'} - ${formatDate(new Date())}`, 50, 780, {
        align: 'center',
        width: 495
    });

    doc.end();
};
